services:
  - type: web
    name: docmind-rag-service
    runtime: python
    rootDir: rag-service
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: LANGFUSE_SECRET_KEY
        sync: false
      - key: LANGFUSE_PUBLIC_KEY
        sync: false
      - key: LANGFUSE_BASE_URL
        sync: false

  - type: web
    name: docmind-backend
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /health
    envVars:
      - key: MONGO_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: RAG_SERVICE_URL
        sync: false
